language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
